# General information about the docs site
site_name: Metabolike
site_url: https://metabolike.readthedocs.io/
site_author: Yi Zhou
copyright: Copyright &copy; 2021 - 2022 Yi Zhou

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/y1zhou
    - icon: simple/googlescholar
      link: https://scholar.google.com/citations?user=afMR9NEAAAAJ
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yizhouuga

# Site navigations
watch:
  - metabolike
nav:
  - Home:
      - index.md
      - usage/installation.md
      - usage/getting_started.md
  # defer to gen-files + literate-nav
  - API references: reference/

# GitHub-related configs
repo_url: https://github.com/y1zhou/metabolike/
repo_name: y1zhou/metabolike
edit_uri: blob/main/docs/

# Theming with mkdocs-material
theme:
  name: material
  logo: _static/metabolike-logo-round.png
  favicon: _static/metabolike-logo-round.png
  font:
    text: Roboto
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [metabolike]
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
            show_submodules: no

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
