# .github/workflows/app.yaml
name: Release to PyPI
on:
  release:
    types:
      - released

jobs:
  release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install flit
        run: python -m pip install flit~=3.0

      - name: Build and publish
        run: flit publish
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          FLIT_INDEX_URL: https://upload.pypi.org/legacy/
